### ISSUE TITLE
Installing with ruby 2.2 fails "uninitalized constant Config"

### ISSUE THREAD

**Issue by MatthewRalston** [helios/bioruby-samtools#52]
Hi, fresh ruby install from RVM on a remote machine during a travis build. Can't build your gem.
https://travis-ci.org/MatthewRalston/SCI/jobs/87806134

**Comment by homonecloco** [comment]
Hi, 
Thanks for reporting this. I need to update the .travis.yml to use the new infrastructure. I got several warnings, but it still (mostly) builds on the current deployment. This is because travis now used docker, and you don't have sudo. There is a workaround to install dependencies, so I'm trying that. 
R.

**Comment by homonecloco** [comment]
I looked at your travis log, you need to have the packages in your .travis.yml To do that, add the following:

```
addons:
  apt:
    packages:
    - update
    - zlib1g-dev
    - libncurses5-dev
    - libtinfo-dev
```

I updated the configuration in this repository, so it can be used as example. 
R.
